---
- name: install our repos
  hosts: all
  become: true

  tasks:

    - name: Make sure systemd-oomd service unit is stopped
      systemd_service:
       state: stopped
       name: systemd-oomd

    - name: remove other files
      include_tasks: yaml_sub/myrepo_clean.yaml
    - name: update file myrepo.repo
      import_tasks: yaml_sub/myrepo_data.yaml

    - name: update system (base)
      dnf:
        name: "*"
        state: latest
        update_cache: true
        skip_broken: true
        nobest: false
        allowerasing: true

    - name: remove other files
      include_tasks: yaml_sub/myrepo_clean.yaml
    - name: update file myrepo.repo
      import_tasks: yaml_sub/myrepo_data.yaml

    - name: update system (all repo)
      dnf:
        name: "*"
        state: latest
        update_cache: true
        skip_broken: true
        nobest: false
        allowerasing: true
        enablerepo: "*"

    - name: Make sure systemd-oomd service unit is started
      systemd_service:
       state: started
       name: systemd-oomd

