---
- name: install desktop stuff 
  hosts: all
  become: true

  tasks:

    - name: remove other files
      include_tasks: yaml_sub/myrepo_clean.yaml
    - name: update file myrepo.repo
      import_tasks: yaml_sub/myrepo_data.yaml

    - name: install movie tools
      dnf:
        name: mencoder mmv mplayer HandBrake
        state: present
        update_cache: true
        skip_broken: true
        nobest: false
        allowerasing: true


