---
- name: mirror cuda 37 repo
  hosts: all
  become: true
  gather_facts: true

  vars: 
    repoid: "cuda_37"
    work_path: "/web/repos/Fedora/AllVersion/{{ repoid }}"    
    src_url: "http://developer.download.nvidia.com/compute/cuda/repos/fedora37/x86_64"

  tasks:

    - name: create directory
      ansible.builtin.file:
        path: "{{ work_path }}"
        state: "directory"

    - name: mirror repo
      shell: "dnf reposync -a x86_64 --delete --download-metadata --norepopath -p {{ work_path }} --repofrompath=x,{{ src_url }} --repoid=x"



