---
- name: mirror docker repo
  hosts: all
  become: true
  gather_facts: true

  vars: 
    repoid: "docker"
    work_path: "/web/repos/Fedora/{{ version }}/{{ repoid }}"
    src_url: "https://download.docker.com/linux/fedora/{{ version }}/x86_64/stable"

  tasks:
    - name: create directory
      ansible.builtin.file:
        path: "{{ work_path }}"
        state: "directory"

    - name: mirror repo
      shell: "dnf reposync --remote-time --newest-only --delete --download-metadata --norepopath -p {{ work_path }} --repofrompath=x,{{ src_url }} --repoid=x"



