---
- name: mirror fedora modular update repo
  hosts: all
  become: true
  gather_facts: true

  vars: 
    repoid: "Fedora_Modular_Update"
    work_path: "/web/repos/Fedora/{{ version }}/{{ repoid }}"
    src_url: "https://ftp.halifax.rwth-aachen.de/fedora/linux/updates/{{ version }}/Modular/x86_64/"

  tasks:
    - name: create directory
      ansible.builtin.file:
        path: "{{ work_path }}"
        state: "directory"

    - name: mirror repo
      shell: "dnf reposync --remote-time --newest-only --delete --download-metadata --norepopath -p {{ work_path }} --repofrompath=x,{{ src_url }} --repoid=x"




