---
- name: mirror fusion free repo
  hosts: all
  become: true
  gather_facts: true

  vars:
    repoid: "fusion_free2"
    work_path: "/web/repos/Fedora/{{ version }}/{{ repoid }}"
    src_url: "http://ftp-stud.hs-esslingen.de/pub/Mirrors/rpmfusion.org/free/fedora/releases/{{ version }}/Everything/x86_64/os"

  tasks:
    - name: create directory
      ansible.builtin.file:
        path: "{{ work_path }}"
        state: "directory"

    - name: mirror repo
      shell: "dnf reposync --remote-time --newest-only --delete --download-metadata --norepopath -p {{ work_path }} --repofrompath=x,{{ src_url }} --repoid=x"
