---
- name: mirror fusion free repo
  hosts: all
  become: true
  gather_facts: true

  vars: 
    work_path: "fusion_free"
    src_url: "rsync://mirror1.hs-esslingen.de/rpmfusion/free/fedora/updates/{{ version }}/x86_64/"
 
  tasks:

    - name: create directory
      ansible.builtin.file:
        path: "{{ base_path }}/{{ version }}/{{ work_path }}"
        state: "directory"

    - name: syncronize
      ansible.posix.synchronize:
        dest: "{{ base_path }}/{{ version }}/{{ work_path }}"
        src: "{{ src_url }}"
        delete: "true"
      delegate_to: "{{ inventory_hostname }}"


