---
- name: mirror vivaldi repo
  hosts: all
  become: true
  gather_facts: true

  vars: 
    repoid: "vivaldi"
    work_path: "/web/repos/Fedora/AllVersion/{{ repoid }}"
    src_url: "https://repo.vivaldi.com/stable/rpm/x86_64/"

  tasks:
    - name: create directory
      ansible.builtin.file:
        path: "{{ work_path }}"
        state: "directory"

    - name: mirror repo
      shell: "dnf reposync --remote-time --newest-only --delete --download-metadata --norepopath -p {{ work_path }} --repofrompath=x,{{ src_url }} --repoid=x"



