---
- name: mirror vscode repo
  hosts: all
  become: true
  gather_facts: true

  vars: 
    repoid: "vscode"
    work_path: "/web/repos/Fedora/AllVersion/{{ repoid }}"
    src_url: "https://packages.microsoft.com/yumrepos/vscode/"

  tasks:
    - name: create directory
      ansible.builtin.file:
        path: "{{ work_path }}"
        state: "directory"

    - name: mirror repo
      shell: "dnf reposync --remote-time --newest-only --delete --download-metadata --norepopath -p {{ work_path }} --repofrompath=x,{{ src_url }} --repoid=x"



